Add support for Whatsapp ID when sending contacts
netflie/whatsapp-cloud-api pull request #41
Opened 2022-09-23 14:34 UTC by vicenterusso

2022-09-23 18:20 UTC, netflie commented
> 

I don't like the param order but I think this option is the best option in order to don't break the API and don't need to release a major version of the package. This will be refactored in future major versions, not problem.

2022-09-23 19:08 UTC, netflie requested changes
Hi!

Thanks for your contributing! Unit tests are mandatory to integrate the PR ^^

2022-09-23 19:08 UTC, aalbarca commented on src/Message/Contact/Phone.php
> +        $this->wa_id = $wa_id ?? $number;
I'm not sure that WhatsApp Id can be replaced by the phone number in all cases. Should the wa_id be nullable?

2022-09-23 19:08 UTC, aalbarca commented on src/Message/Contact/Phone.php
> +    public function wa_id(): string
We're using camelCase for method naming

2022-09-25 05:19 UTC, vicenterusso commented on src/Message/Contact/Phone.php
> +        $this->wa_id = $wa_id ?? $number;
According to [documentation](https://developers.facebook.com/docs/whatsapp/on-premises/reference/contacts) I think we can safely say that Whatsapp User ID is in indeed the phone number.

Not sure about the nullable. Probably it's better not being set if not sharing a non whatsapp number

2022-09-27 21:10 UTC, netflie approved these changes

2022-09-27 21:12 UTC, netflie commented on src/Message/Contact/Phone.php
> +        $this->wa_id = $wa_id ?? '';
```suggestion
        $this->wa_id = $wa_id;
```

2022-09-27 21:12 UTC, netflie commented on src/Message/Contact/Phone.php
> +    public function __construct(string $number, PhoneType $type, string $wa_id = null)
```suggestion
    public function __construct(string $number, PhoneType $type, string $wa_id = '')
```

2022-09-27 21:12 UTC, netflie commented on src/Request/RequestContactMessage.php
> +            if(!empty($phone->waId())) {
```suggestion
            if (!empty($phone->waId())) {
```

2022-09-27 21:15 UTC, netflie commented on src/Request/RequestContactMessage.php
> +
```suggestion
```

2022-09-27 21:19 UTC, netflie approved these changes

2022-09-27 21:20 UTC, merged